config/routes.rb
Rails.application.routes.draw do
  get "pages/contact"

  resources :diaries do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
  end

  get "index_user", to: "catches#index_user"
  get "index_user/autocomplete", to: "catches#autocomplete_index_user"

  resources :catches do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
    resource :like, only: [ :create, :destroy ]
    resources :comments, only: [ :new, :create, :index, :destroy, :edit, :update ]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root "home#index"

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users
    resources :catches
    resources :diaries
  end

  get "terms", to: "home#terms"
  get "privacy_policy", to: "home#privacy_policy"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :require_admin

  def index ;end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<div class="py-24 md:py-24 lg:py-8">
  <!-- Tittle -->
  <div class="flex items-center justify-between max-w-screen-xl mx-auto px-3 mb-6">
    <h5 class="text-lg md:text-xl font-bold leading-none text-gray-900 dark:text-white">Admin Dashboard</h5>
  </div>
  <div class="flex flex-col items-center justify-center px-3 w-full max-w-screen-xl mx-auto">
    <div class="w-full grid grid-cols-1 lg:grid-cols-2 lg:gap-6">
      <!-- Card 1 -->
      <div class="mb-6 md:mb-6 lg:mb-0 flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full max-w-screen-xl mx-auto hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-900">
          <img class="object-cover w-full rounded-t-lg h-32 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="/1.png" alt="">
          <div class="w-full flex flex-col justify-between p-4 leading-normal">
              <h5 class="w-full mb-2 text-base md:text-lg font-bold tracking-tight text-gray-900 dark:text-white">User Management</h5>
              <p class="w-full mb-3 text-sm md:text-base font-normal text-gray-700 dark:text-gray-400">You can manage Users' Account from here.</p>
              <%= link_to admin_users_path, class: "block w-full md:w-auto text-white bg-gray-800 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm md:text-base px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                Details of Users
              <% end %>
          </div>
      </div>

      <!-- Card 2 -->
      <div class="mb-6 md:mb-6 lg:mb-0 flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full max-w-screen-xl mx-auto hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-900">
          <img class="object-cover w-full rounded-t-lg h-32 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="/1.png" alt="">
          <div class="w-full flex flex-col justify-between p-4 leading-normal">
              <h5 class="w-full mb-2 text-base md:text-lg font-bold tracking-tight text-gray-900 dark:text-white">Catch Management</h5>
              <p class="w-full mb-3 text-sm md:text-base font-normal text-gray-700 dark:text-gray-400">You can manage Catches from here.</p>
              <%= link_to admin_catches_path, class: "block w-full md:w-auto text-white bg-gray-800 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm md:text-base px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                Details of Catches
              <% end %>
          </div>
      </div>

      <!-- Card 3 -->
      <div class="mb-6 md:mb-6 lg:mb-0 flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full max-w-screen-xl mx-auto hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-900">
          <img class="object-cover w-full rounded-t-lg h-32 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="/1.png" alt="">
          <div class="w-full flex flex-col justify-between p-4 leading-normal">
              <h5 class="w-full mb-2 text-base md:text-lg font-bold tracking-tight text-gray-900 dark:text-white">Diary Management</h5>
              <p class="w-full mb-3 text-sm md:text-base font-normal text-gray-700 dark:text-gray-400">You can manage Diaries from here.</p>
              <%= link_to admin_diaries_path, class: "block w-full md:w-auto text-white bg-gray-800 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm md:text-base px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                Details of Diaries
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>