config/routes.rb
Rails.application.routes.draw do
  get "pages/contact"

  resources :diaries do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
  end

  get "index_user", to: "catches#index_user"
  get "index_user/autocomplete", to: "catches#autocomplete_index_user"

  resources :catches do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
    resource :like, only: [ :create, :destroy ]
    resources :comments, only: [ :new, :create, :index, :destroy, :edit, :update ]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root "home#index"

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users
    resources :catches
    resources :diaries
  end

  get "terms", to: "home#terms"
  get "privacy_policy", to: "home#privacy_policy"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/catch.rb
class Catch < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :tide, presence: true
  validates :tide_level, presence: true
  validates :range, presence: true
  validates :size, presence: true

  enum :tide,       { "大潮" => 0, "中潮" => 1, "小潮" => 2, "若潮" => 3, "長潮" => 4 }
  enum :tide_level, { "満潮前後" => 0, "上げ前半" => 1, "上げ後半" => 2, "干潮前後" => 3, "下げ前半" => 4, "下げ後半" => 5 }
  enum :range,      { "トップ" => 0, "表層" => 1, "中層" => 2, "ボトム" => 3 }
  enum :size,       { "20cm以下" => 0, "20~30cm" => 1, "30~40cm" => 2, "40~50cm" => 3, "50~60cm" => 4, "60~70cm" => 5, "70~80cm" => 6, "80~90cm" => 7, "90cm以上" => 8 }

  def self.ransackable_attributes(auth_object = nil)
    [ "memo", "range", "size", "tide", "tide_level" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "comments" ]
  end

  ransacker :tide, formatter: proc { |v| tides[v] } do |parent|
    parent.table[:tide]
  end

  ransacker :tide_level, formatter: proc { |v| tide_levels[v] } do |parent|
    parent.table[:tide_level]
  end

  ransacker :range, formatter: proc { |v| ranges[v] } do |parent|
    parent.table[:range]
  end

  ransacker :size, formatter: proc { |v| sizes[v] } do |parent|
    parent.table[:size]
  end
end

app/controllers/admin/catches_controller.rb
class Admin::CatchesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :require_admin
  before_action :set_catch, only: %i[show destroy]

  def index
    @catches = Catch.includes(:user, images_attachments: :blob).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(dom_id(@catch, :admin_show), partial: "admin/catches/admin_show", locals: { catch: @catch })
      }
      format.html
    end
  end

  def destroy
    @catch.destroy
    respond_to do |format|
      format.turbo_stream {
        flash.now[:notice] = I18n.t("admin.catch.destroy.success")
        render turbo_stream: [
          turbo_stream.remove(dom_id(@catch, :admin)),
          turbo_stream.update("flash", partial: "shared/flash")
        ]
      }
      format.html
    end
  end

  private

  def set_catch
    @catch = Catch.includes(:user, images_attachments: :blob).find(params[:id])
  end
end

app/controllers/catches_controller.rb
class CatchesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!, except: %i[index show new create autocomplete]
  before_action :set_catch, only: %i[show edit update destroy purge_image]
  before_action :correct_user, only: %i[edit update destroy purge_image]

  def new
    @catch = current_user ? current_user.catches.build : Catch.new
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: @catch })
      }
      format.html
    end
  end

  def create
    if user_signed_in?
      @catch = current_user.catches.build(catch_params)
      if @catch.save
        respond_to do |format|
          format.turbo_stream {
            flash.now[:notice] = I18n.t("activerecord.attributes.catch.create.success")
            render turbo_stream: [
              turbo_stream.prepend("catch_index", partial: "catches/index_content", locals: { catch: @catch }),
              turbo_stream.prepend("catch_index_user", partial: "catches/index_content", locals: { catch: @catch }),
              turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: Catch.new }),
              turbo_stream.update("flash", partial: "shared/flash")
            ]
          }
          format.html { redirect_to catches_path, notice: I18n.t("activerecord.attributes.catch.create.success") }
        end
      else
        respond_to do |format|
          format.turbo_stream {
            flash.now[:alert] = I18n.t("activerecord.attributes.catch.create.failure")
            render turbo_stream: [
              turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: @catch }),
              turbo_stream.update("flash", partial: "shared/flash")
            ]
          }
          format.html { render :new, alert: I18n.t("activerecord.attributes.catch.create.failure") }
        end
      end
    else
      respond_to do |format|
        format.turbo_stream {
          flash.now[:alert] = I18n.t("devise.failure.unauthenticated")
          render turbo_stream: [
            turbo_stream.update("flash", partial: "shared/flash"),
            turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: Catch.new })
          ]
        }
        format.html { redirect_to new_user_session_path, alert: I18n.t("devise.failure.unauthenticated") }
      end
    end
  end

  def index
    search_params = params.fetch(:q, {}).permit(:memo_cont, :tide_eq, :tide_level_eq, :range_eq, :size_eq)
    @search = Catch.ransack(search_params)
    @catches = @search.result(distinct: true).includes(:user, :comments, images_attachments: :blob).order(created_at: :desc).page(params[:page]).per(8)
  end

  def index_user
    search_params = params.fetch(:q, {}).permit(:memo_cont, :tide_eq, :tide_level_eq, :range_eq, :size_eq)
    @search = current_user.catches.ransack(search_params)
    @catches = @search.result(distinct: true).includes(:user, :comments, images_attachments: :blob).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(dom_id(@catch, :show), partial: "catches/show", locals: { catch: @catch })
      }
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(dom_id(@catch, :edit), partial: "catches/edit", locals: { catch: @catch })
      }
      format.html
    end
  end

  def update
    if @catch.update(catch_params.except(:images))
      attach_images if params[:catch][:images]
      respond_to do |format|
        format.turbo_stream {
          flash.now[:notice] = I18n.t("activerecord.attributes.catch.update.success")
          render turbo_stream: [
            turbo_stream.update(dom_id(@catch, :details), partial: "catches/show_details", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :images), partial: "catches/show_images", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :index_image), partial: "catches/index_image", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :memo), partial: "catches/index_memo", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :edit), partial: "catches/edit", locals: { catch: @catch }),
            turbo_stream.update("flash", partial: "shared/flash")
          ]
        }
        format.html { redirect_to @catch, notice: I18n.t("activerecord.attributes.catch.update.success") }
      end
    else
      respond_to do |format|
        format.turbo_stream {
          flash.now[:alert] = I18n.t("activerecord.attributes.catch.update.failure")
          render turbo_stream: [
            turbo_stream.replace(dom_id(@catch, :edit), partial: "catches/edit", locals: { catch: @catch }),
            turbo_stream.update("flash", partial: "shared/flash")
          ]
        }
        format.html { render :edit, notice: I18n.t("activerecord.attributes.catch.update.failure") }
      end
    end
  end

  def destroy
    @catch.destroy
    respond_to do |format|
      format.turbo_stream {
        flash.now[:notice] = I18n.t("activerecord.attributes.catch.destroy.success")
        render turbo_stream: [
          turbo_stream.remove(dom_id(@catch)),
          turbo_stream.update("flash", partial: "shared/flash")
        ]
      }
      format.html { redirect_to catches_path, notice: I18n.t("activerecord.attributes.catch.destroy.success") }
    end
  end

  def purge_image
    image = @catch.images.find(params[:image_id])
    image_id = image.id
    image.purge
    respond_to do |format|
      format.turbo_stream {
        flash.now[:notice] = I18n.t("activerecord.attributes.catch.purge_image.success")
        render turbo_stream: [
          turbo_stream.remove(dom_id(@catch, :slide)),
          turbo_stream.remove(dom_id(@catch, :carousel_link)),
          turbo_stream.update("flash", partial: "shared/flash")
        ]
      }
      format.html { redirect_to edit_catch_path(@catch), notice: I18n.t("activerecord.attributes.catch.purge_image.success") }
    end
  end

  def autocomplete
    query = params[:q]
    suggestions = Catch.where("memo LIKE ?", "%#{query}%").limit(10).pluck(:memo)
    render json: suggestions
  end

  def autocomplete_index_user
    query = params[:q]
    suggestions = current_user.catches.where("memo LIKE ?", "%#{query}%").limit(10).pluck(:memo)
    render json: suggestions
  end

  private

  def catch_params
    params.require(:catch).permit(:tide, :tide_level, :range, :size, :memo, :latitude, :longitude, images: [])
  end

  def set_catch
    @catch = Catch.includes(:user, images_attachments: :blob).find(params[:id])
  end

  def attach_images
    params[:catch][:images].each do |image|
      @catch.images.attach(image)
    end
  end

  def correct_user
    unless @catch.user == current_user
      redirect_to catches_path, notice: I18n.t("activerecord.attributes.catch.correct_user")
    end
  end
end

app/helpers/admin/catches_helper.rb
module Admin::CatchesHelper
end

app/helpers/catches_helper.rb
module CatchesHelper
end

app/views/catches/_edit.html.erb
<%= turbo_frame_tag dom_id(catch, :edit) do %>
  <%= render partial: 'catches/edit_images', locals: { catch: catch } %>
  <%= render partial: "catches/form", locals: { catch: catch } %>
<% end %>

app/views/catches/_index_content.html.erb
<div id="<%= dom_id(catch) %>" class="flex flex-col md:flex-row items-center bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-900 w-full max-w-full">
  <!-- Image (Partial)  -->
  <div id="<%= dom_id(catch, :index_image) %>" class="w-full md:w-48 h-32 md:h-64 flex-shrink-0">
    <%= render 'index_image', catch: catch %>
  </div>
  <!-- Info -->
  <div class="flex flex-col justify-between p-4 md:px-6 w-full leading-normal">
    <!-- User image and name -->
    <div class="flex items-center mb-4">
      <div class="flex-shrink-0">
        <%= image_tag catch.user.profile_image, class: "w-10 h-10 md:w-12 md:h-12 xl:w-13 xl:h-13 rounded-full object-cover", alt: "#{catch.user.username} profile image" %>
      </div>
      <div class="ml-4">
        <p class="text-sm md:text-base font-medium text-gray-900 dark:text-white"><%= catch.user.username %></p>
        <p class="text-sm md:text-base text-gray-500 dark:text-gray-400">
          <%= catch.created_at.in_time_zone('Asia/Tokyo').strftime("%Y年%-m月%-d日 %-H時%-M分") %>
        </p>
      </div>
    </div>
    <!-- Memo (Partial) -->
    <div id="<%= dom_id(catch, :memo) %>">
      <%= render 'index_memo', catch: catch %>
    </div>
    <!-- Detail button -->
    <button data-modal-target="<%= dom_id(catch, :modal) %>" data-modal-toggle="<%= dom_id(catch, :modal) %>" class="block w-full md:w-auto text-white bg-gray-900 hover:bg-blue-900 focus:ring-4 focus:outline-none focus:ring-blue-900 font-medium rounded-lg text-sm md:text-base px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-blue-900 dark:focus:ring-blue-900">
      詳しく見る
    </button>
  </div>
</div>

<!-- Detail modal -->
<div id="<%= dom_id(catch, :modal) %>" data-controller="catchdestroy" data-catchdestroy-modal-id-value="<%= dom_id(catch, :modal) %>" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-5rem)] max-h-full">
  <div class="relative w-full max-w-4xl max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-800">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <%= image_tag catch.user.profile_image, class: "w-10 h-10 md:w-12 md:h-12 xl:w-13 xl:h-13 rounded-full object-cover", alt: "#{catch.user.username} profile image" %>
          </div>
          <div class="ml-4">
            <p class="text-sm md:text-base font-medium text-gray-900 dark:text-white"><%= catch.user.username %></p>
            <p class="text-sm md:text-base text-gray-500 dark:text-gray-400"><%= catch.created_at.in_time_zone('Asia/Tokyo').strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
          </div>
        </div>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="<%= dom_id(catch, :modal) %>">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-4 md:p-5 space-y-4">
        <%= turbo_frame_tag dom_id(catch, :show), src: catch_path(catch, format: :turbo_stream) %>
      </div>
      <!-- Modal footer -->
      <div class="flex justify-end p-4 md:p-5 gap-3 border-t border-gray-200 rounded-b dark:border-gray-600 text-sm md:text-base">
        <div class="grid grid-cols-2 gap-4 w-full md:flex md:space-x-3 md:gap-0 md:justify-end">
          <!-- Comment button -->     
          <button data-modal-target="commentmodal_<%= catch.id %>" data-modal-toggle="commentmodal_<%= catch.id %>" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-gray-600 dark:focus:ring-blue-800 border dark:border-gray-600">コメント<%= " (#{catch.comments.size})" if catch.comments.any? %></button>
          <!-- Nice Catch button -->         
          <%= render partial: 'likes/like_button', locals: { catch: catch } %>
          <% if current_user == catch.user %>
            <!-- Edit button -->   
            <button data-modal-target="catcheditmodal_<%= catch.id %>" data-modal-toggle="catcheditmodal_<%= catch.id %>" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-gray-600 dark:focus:ring-blue-800 border dark:border-gray-600">編集</button>
            <!-- Delete button -->   
            <%= button_to catch, method: :delete, data: { turbo_method: :delete, turbo_confirm: t('activerecord.attributes.catch.show.confirm') }, class: 'w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-gray-600 dark:focus:ring-blue-800 border dark:border-gray-600' do %>削除<% end %>
          <% end %>
          <!-- Close button -->   
          <button data-modal-hide="<%= dom_id(catch, :modal) %>" type="button" class="col-span-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-gray-600 dark:focus:ring-blue-800 border dark:border-gray-600">閉じる</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- edit modal -->
<% if current_user == catch.user %>
<div id="catcheditmodal_<%= catch.id %>" data-catcheditmodal-catch-id-value="<%= catch.id %>" data-catcheditmodal-target="catcheditmodal" data-controller="catcheditmodal" data-action="click->hello#stopToggle" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-5rem)] max-h-full" data-controller="record">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-800">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <%= image_tag catch.user.profile_image, class: "w-10 h-10 md:w-12 md:h-12 xl:w-13 xl:h-13 rounded-full object-cover", alt: "#{catch.user.username} profile image" %>
                  </div>
                  <div class="ml-4">
                    <p class="text-sm md:text-base font-medium text-gray-900 dark:text-white">編集中</p>
                    <p class="text-sm md:text-base text-gray-500 dark:text-gray-400">
                      <%= catch.created_at.in_time_zone('Asia/Tokyo').strftime("%Y年%-m月%-d日 %-H時%-M分") %>
                    </p>
                  </div>
                </div>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="catcheditmodal_<%= catch.id %>">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5 space-y-4">
                <%= turbo_frame_tag dom_id(catch, :edit), src: edit_catch_path(catch, format: :turbo_stream) %>
            </div>
            <!-- Modal footer -->
            <div class="flex items-center justify-end p-4 md:p-5 space-x-3 rtl:space-x-reverse border-t border-gray-200 rounded-b dark:border-gray-600">
                <button data-modal-hide="catcheditmodal_<%= catch.id %>"  type="button" class="py-2.5 px-5 ms-3 text-sm md:text-base font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">閉じる</button>
            </div>
        </div>
    </div>
</div>
<% end %>

<!-- Comment modal -->
<div id="commentmodal_<%= catch.id %>" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-5rem)] max-h-full">
  <div class="relative w-full max-w-xl max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <div class="flex items-center">
          <p class="text-sm md:text-base font-medium text-gray-900 dark:text-white">この釣果のコメント</p>
        </div>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="commentmodal_<%= catch.id %>">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-4 md:p-5 space-y-4">
        <%= turbo_frame_tag dom_id(catch, :comments), src: catch_comments_path(catch, format: :turbo_stream) %>
      </div>
      <!-- Modal footer -->
      <div class="p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600 text-sm md:text-base">
        <%= turbo_frame_tag dom_id(catch, :new_comment_form), src: new_catch_comment_path(catch, format: :turbo_stream), class: "w-full" %>
      </div>
    </div>
  </div>
</div>

app/views/catches/_index_image.html.erb
<% if catch.images.attached? %>
    <%= image_tag catch.images.first, class: "object-cover w-full h-full rounded-t-lg md:rounded-none md:rounded-s-lg", alt: "Catch Image" %>
<% else %>
    <img src="/index.png" class="object-cover w-full h-full rounded-t-lg md:rounded-none md:rounded-s-lg" alt="Default Image">
<% end %>

app/views/catches/_index_memo.html.erb
<% if catch.memo.present? %>
  <p class="mb-3 text-sm md:text-base font-normal text-gray-700 dark:text-gray-400">
    <%= catch.memo %>
  </p>
<% end %>

app/views/catches/_new.html.erb
<%= turbo_frame_tag "new_catch_form" do %>
  <%= render partial: "catches/form", locals: { catch: catch } %>
<% end %>

app/views/catches/_search_form.html.erb
<%= search_form_for q, url: url, html: { class: "max-w-screen-xl mx-auto px-3 py-6" } do |f| %>
  <label for="default-search" class="mb-2 text-sm md:text-base font-medium text-gray-900 sr-only dark:text-white">Search</label>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>
    <%= f.search_field :memo_or_tide_cont, id: "default-search", class: "block w-full p-4 ps-10 text-base text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Search Mockups, Logos...", required: true %>
    <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-900 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm md:text-base px-4 py-2 dark:bg-blue-900 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
  </div>
<% end %>

app/views/catches/_show.html.erb
<div class="flex flex-col items-center items-stretch rounded-lg md:flex-row md:max-w-screen-xl mx-auto" data-action="click->hello#stopToggle">
  <div id="<%= dom_id(catch, :images) %>" class="w-full md:w-1/2 h-72 md:h-96 md:w-58 rounded-lg overflow-hidden bg-gray-800">
    <%= render 'show_images', catch: catch %>
  </div>
  <div id="<%= dom_id(catch, :details) %>" class="flex md:w-1/2 flex-col justify-start mt-6 md:mt-0 md:px-6 leading-normal w-full">
    <%= render 'show_details', catch: catch %>
  </div>
</div>

app/views/catches/edit.html.erb
<%= render 'edit', catch: @catch %>

app/views/catches/show.html.erb
<%= render 'show', catch: @catch %>

app/views/catches/user_index.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-3 mx-auto">
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-900 dark:border-gray-700">
      <div class="p-6 space-y-3 md:space-y-6 sm:p-8">
        <!-- title -->
        <span class="text-2xl font-extrabold tracking-tight">Your</span>
        <span class="ms-1 text-base font-normal text-gray-500 dark:text-gray-400">catches</span>
        <!-- list of catches -->
        <div class="flow-root">
            <ul role="list">
              <%= turbo_frame_tag "user_catches" do %>
                <%= render 'user_catch' %>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
</section>