config/routes.rb
Rails.application.routes.draw do
  get "pages/contact"

  resources :diaries do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
  end

  get "index_user", to: "catches#index_user"
  get "index_user/autocomplete", to: "catches#autocomplete_index_user"

  resources :catches do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
    resource :like, only: [ :create, :destroy ]
    resources :comments, only: [ :new, :create, :index, :destroy, :edit, :update ]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root "home#index"

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users
    resources :catches
    resources :diaries
  end

  get "terms", to: "home#terms"
  get "privacy_policy", to: "home#privacy_policy"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/catch.rb
class Catch < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :tide, presence: true
  validates :tide_level, presence: true
  validates :range, presence: true
  validates :size, presence: true

  enum :tide,       { "大潮" => 0, "中潮" => 1, "小潮" => 2, "若潮" => 3, "長潮" => 4 }
  enum :tide_level, { "満潮前後" => 0, "上げ前半" => 1, "上げ後半" => 2, "干潮前後" => 3, "下げ前半" => 4, "下げ後半" => 5 }
  enum :range,      { "トップ" => 0, "表層" => 1, "中層" => 2, "ボトム" => 3 }
  enum :size,       { "20cm以下" => 0, "20~30cm" => 1, "30~40cm" => 2, "40~50cm" => 3, "50~60cm" => 4, "60~70cm" => 5, "70~80cm" => 6, "80~90cm" => 7, "90cm以上" => 8 }

  def self.ransackable_attributes(auth_object = nil)
    [ "memo", "range", "size", "tide", "tide_level" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "comments" ]
  end

  ransacker :tide, formatter: proc { |v| tides[v] } do |parent|
    parent.table[:tide]
  end

  ransacker :tide_level, formatter: proc { |v| tide_levels[v] } do |parent|
    parent.table[:tide_level]
  end

  ransacker :range, formatter: proc { |v| ranges[v] } do |parent|
    parent.table[:range]
  end

  ransacker :size, formatter: proc { |v| sizes[v] } do |parent|
    parent.table[:size]
  end
end

app/controllers/admin/catches_controller.rb
class Admin::CatchesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :require_admin
  before_action :set_catch, only: %i[show destroy]

  def index
    @catches = Catch.includes(:user, images_attachments: :blob).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(dom_id(@catch, :admin_show), partial: "admin/catches/admin_show", locals: { catch: @catch })
      }
      format.html
    end
  end

  def destroy
    @catch.destroy
    respond_to do |format|
      format.turbo_stream {
        flash.now[:notice] = I18n.t("admin.catch.destroy.success")
        render turbo_stream: [
          turbo_stream.remove(dom_id(@catch, :admin)),
          turbo_stream.update("flash", partial: "shared/flash")
        ]
      }
      format.html
    end
  end

  private

  def set_catch
    @catch = Catch.includes(:user, images_attachments: :blob).find(params[:id])
  end
end

app/controllers/catches_controller.rb
class CatchesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!, except: %i[index show new create autocomplete]
  before_action :set_catch, only: %i[show edit update destroy purge_image]
  before_action :correct_user, only: %i[edit update destroy purge_image]

  def new
    @catch = current_user ? current_user.catches.build : Catch.new
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: @catch })
      }
      format.html
    end
  end

  def create
    if user_signed_in?
      @catch = current_user.catches.build(catch_params)
      if @catch.save
        respond_to do |format|
          format.turbo_stream {
            flash.now[:notice] = I18n.t("activerecord.attributes.catch.create.success")
            render turbo_stream: [
              turbo_stream.prepend("catch_index", partial: "catches/index_content", locals: { catch: @catch }),
              turbo_stream.prepend("catch_index_user", partial: "catches/index_content", locals: { catch: @catch }),
              turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: Catch.new }),
              turbo_stream.update("flash", partial: "shared/flash")
            ]
          }
          format.html { redirect_to catches_path, notice: I18n.t("activerecord.attributes.catch.create.success") }
        end
      else
        respond_to do |format|
          format.turbo_stream {
            flash.now[:alert] = I18n.t("activerecord.attributes.catch.create.failure")
            render turbo_stream: [
              turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: @catch }),
              turbo_stream.update("flash", partial: "shared/flash")
            ]
          }
          format.html { render :new, alert: I18n.t("activerecord.attributes.catch.create.failure") }
        end
      end
    else
      respond_to do |format|
        format.turbo_stream {
          flash.now[:alert] = I18n.t("devise.failure.unauthenticated")
          render turbo_stream: [
            turbo_stream.update("flash", partial: "shared/flash"),
            turbo_stream.replace("new_catch_form", partial: "catches/new", locals: { catch: Catch.new })
          ]
        }
        format.html { redirect_to new_user_session_path, alert: I18n.t("devise.failure.unauthenticated") }
      end
    end
  end

  def index
    search_params = params.fetch(:q, {}).permit(:memo_cont, :tide_eq, :tide_level_eq, :range_eq, :size_eq)
    @search = Catch.ransack(search_params)
    @catches = @search.result(distinct: true).includes(:user, :comments, images_attachments: :blob).order(created_at: :desc).page(params[:page]).per(8)
  end

  def index_user
    search_params = params.fetch(:q, {}).permit(:memo_cont, :tide_eq, :tide_level_eq, :range_eq, :size_eq)
    @search = current_user.catches.ransack(search_params)
    @catches = @search.result(distinct: true).includes(:user, :comments, images_attachments: :blob).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(dom_id(@catch, :show), partial: "catches/show", locals: { catch: @catch })
      }
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(dom_id(@catch, :edit), partial: "catches/edit", locals: { catch: @catch })
      }
      format.html
    end
  end

  def update
    if @catch.update(catch_params.except(:images))
      attach_images if params[:catch][:images]
      respond_to do |format|
        format.turbo_stream {
          flash.now[:notice] = I18n.t("activerecord.attributes.catch.update.success")
          render turbo_stream: [
            turbo_stream.update(dom_id(@catch, :details), partial: "catches/show_details", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :images), partial: "catches/show_images", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :index_image), partial: "catches/index_image", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :memo), partial: "catches/index_memo", locals: { catch: @catch }),
            turbo_stream.update(dom_id(@catch, :edit), partial: "catches/edit", locals: { catch: @catch }),
            turbo_stream.update("flash", partial: "shared/flash")
          ]
        }
        format.html { redirect_to @catch, notice: I18n.t("activerecord.attributes.catch.update.success") }
      end
    else
      respond_to do |format|
        format.turbo_stream {
          flash.now[:alert] = I18n.t("activerecord.attributes.catch.update.failure")
          render turbo_stream: [
            turbo_stream.replace(dom_id(@catch, :edit), partial: "catches/edit", locals: { catch: @catch }),
            turbo_stream.update("flash", partial: "shared/flash")
          ]
        }
        format.html { render :edit, notice: I18n.t("activerecord.attributes.catch.update.failure") }
      end
    end
  end

  def destroy
    @catch.destroy
    respond_to do |format|
      format.turbo_stream {
        flash.now[:notice] = I18n.t("activerecord.attributes.catch.destroy.success")
        render turbo_stream: [
          turbo_stream.remove(dom_id(@catch)),
          turbo_stream.update("flash", partial: "shared/flash")
        ]
      }
      format.html { redirect_to catches_path, notice: I18n.t("activerecord.attributes.catch.destroy.success") }
    end
  end

  def purge_image
    image = @catch.images.find(params[:image_id])
    image_id = image.id
    image.purge
    respond_to do |format|
      format.turbo_stream {
        flash.now[:notice] = I18n.t("activerecord.attributes.catch.purge_image.success")
        render turbo_stream: [
          turbo_stream.remove(dom_id(@catch, :slide)),
          turbo_stream.remove(dom_id(@catch, :carousel_link)),
          turbo_stream.update("flash", partial: "shared/flash")
        ]
      }
      format.html { redirect_to edit_catch_path(@catch), notice: I18n.t("activerecord.attributes.catch.purge_image.success") }
    end
  end

  def autocomplete
    query = params[:q]
    suggestions = Catch.where("memo LIKE ?", "%#{query}%").limit(10).pluck(:memo)
    render json: suggestions
  end

  def autocomplete_index_user
    query = params[:q]
    suggestions = current_user.catches.where("memo LIKE ?", "%#{query}%").limit(10).pluck(:memo)
    render json: suggestions
  end

  private

  def catch_params
    params.require(:catch).permit(:tide, :tide_level, :range, :size, :memo, :latitude, :longitude, images: [])
  end

  def set_catch
    @catch = Catch.includes(:user, images_attachments: :blob).find(params[:id])
  end

  def attach_images
    params[:catch][:images].each do |image|
      @catch.images.attach(image)
    end
  end

  def correct_user
    unless @catch.user == current_user
      redirect_to catches_path, notice: I18n.t("activerecord.attributes.catch.correct_user")
    end
  end
end

app/helpers/admin/catches_helper.rb
module Admin::CatchesHelper
end

app/helpers/catches_helper.rb
module CatchesHelper
end

app/views/admin/catches/_admin_index_content.html.erb
<div id="<%= dom_id(catch, :admin) %>" class="flex flex-col md:flex-row items-center bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-900 w-full max-w-full">
  <div class="w-full md:w-48 h-32 md:h-64 flex-shrink-0">
    <% if catch.images.attached? %>
        <%= image_tag catch.images.first, class: "object-cover w-full h-full rounded-t-lg md:rounded-none md:rounded-s-lg", alt: "Catch Image" %>
    <% else %>
        <img src="/index.png" class="object-cover w-full h-full rounded-t-lg md:rounded-none md:rounded-s-lg" alt="Default Image">
    <% end %>
  </div>
  <!-- Info -->
  <div class="flex flex-col justify-between p-4 md:px-6 w-full leading-normal">
    <!-- User image and name -->
    <div class="flex items-center mb-4">
      <div class="flex-shrink-0">
        <%= image_tag catch.user.profile_image, class: "w-10 h-10 md:w-12 md:h-12 xl:w-13 xl:h-13 rounded-full object-cover", alt: "#{catch.user.username} profile image" %>
      </div>
      <div class="ml-4">
        <p class="text-sm md:text-base font-medium text-gray-900 dark:text-white"><%= catch.user.username %></p>
        <p class="text-sm md:text-base text-gray-500 dark:text-gray-400">
          <%= catch.created_at.in_time_zone('Asia/Tokyo').strftime("%Y年%-m月%-d日 %-H時%-M分") %>
        </p>
      </div>
    </div>
    <% if catch.memo.present? %>
      <p class="mb-3 text-sm md:text-base font-normal text-gray-700 dark:text-gray-400">
        <%= catch.memo %>
      </p>
    <% end %>
    <!-- Detail button -->
    <button data-modal-target="<%= dom_id(catch, :modal) %>" data-modal-toggle="<%= dom_id(catch, :modal) %>" class="block w-full md:w-auto text-white bg-gray-900 hover:bg-blue-900 focus:ring-4 focus:outline-none focus:ring-blue-900 font-medium rounded-lg text-sm md:text-base px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-blue-900 dark:focus:ring-blue-900">
      詳しく見る
    </button>
  </div>
</div>

<!-- Detail modal -->
<div id="<%= dom_id(catch, :modal) %>" data-controller="catchdestroy" data-catchdestroy-modal-id-value="<%= dom_id(catch, :modal) %>" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-5rem)] max-h-full">
  <div class="relative w-full max-w-4xl max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-800">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <%= image_tag catch.user.profile_image, class: "w-10 h-10 md:w-12 md:h-12 xl:w-13 xl:h-13 rounded-full object-cover", alt: "#{catch.user.username} profile image" %>
          </div>
          <div class="ml-4">
            <p class="text-sm md:text-base font-medium text-gray-900 dark:text-white"><%= catch.user.username %></p>
            <p class="text-sm md:text-base text-gray-500 dark:text-gray-400"><%= catch.created_at.in_time_zone('Asia/Tokyo').strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
          </div>
        </div>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="<%= dom_id(catch, :modal) %>">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-4 md:p-5 space-y-4">
        <%= turbo_frame_tag dom_id(catch, :admin_show), src: admin_catch_path(catch, format: :turbo_stream) %>
      </div>
      <!-- Modal footer -->
      <div class="flex justify-end p-4 md:p-5 gap-3 border-t border-gray-200 rounded-b dark:border-gray-600 text-sm md:text-base">
        <div class="grid grid-cols-2 gap-4 w-full md:flex md:space-x-3 md:gap-0 md:justify-end">
          <!-- Delete button -->   
          <%= button_to admin_catch_path(catch), method: :delete, data: { turbo_method: :delete, turbo_confirm: t('activerecord.attributes.catch.show.confirm') }, class: 'w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-gray-600 dark:focus:ring-blue-800 border dark:border-gray-600' do %>削除<% end %>
          <!-- Close button -->   
          <button data-modal-hide="<%= dom_id(catch, :modal) %>" type="button" class="col-span-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-gray-800 dark:hover:bg-gray-600 dark:focus:ring-blue-800 border dark:border-gray-600">閉じる</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/catches/_admin_show.html.erb
<div class="flex flex-col items-center items-stretch rounded-lg md:flex-row md:max-w-screen-xl mx-auto" data-action="click->hello#stopToggle">
  <div id="<%= dom_id(catch, :admin_images) %>" class="w-full md:w-1/2 h-72 md:h-96 md:w-58 rounded-lg overflow-hidden bg-gray-800">
    <%= render 'admin_show_images', catch: catch %>
  </div>
  <div id="<%= dom_id(catch, :admin_details) %>" class="flex md:w-1/2 flex-col justify-start mt-6 md:mt-0 md:px-6 leading-normal w-full">
    <%= render 'admin_show_details', catch: catch %>
  </div>
</div>

app/views/admin/catches/_admin_show_details.html.erb
<div class="grid gap-4 grid-cols-2">

  <!-- Tide -->
  <div class="w-full">
    <div class="block mb-2 text-sm md:text-base font-medium text-gray-900 dark:text-white">
      <%= t('activerecord.attributes.catch.new.tide_prompt') %>
    </div>
    <div class="bg-gray-50 border border-gray-300 text-gray-900 text-sm md:text-base rounded-lg p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      <%= catch.tide %>
    </div>
  </div>

  <!-- Tide Level -->
  <div class="w-full">
    <div class="block mb-2 text-sm md:text-base font-medium text-gray-900 dark:text-white">
      <%= t('activerecord.attributes.catch.new.tide_level_prompt') %>
    </div>
    <div class="bg-gray-50 border border-gray-300 text-gray-900 text-sm md:text-base rounded-lg p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      <%= catch.tide_level %>
    </div>
  </div>

  <!-- Range -->
  <div class="w-full">
    <div class="block mb-2 text-sm md:text-base font-medium text-gray-900 dark:text-white">
      <%= t('activerecord.attributes.catch.new.range_prompt') %>
    </div>
    <div class="bg-gray-50 border border-gray-300 text-gray-900 text-sm md:text-base xl:text-lg rounded-lg p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      <%= catch.range %>
    </div>
  </div>

  <!-- Size -->
  <div class="w-full">
    <div class="block mb-2 text-sm md:text-base font-medium text-gray-900 dark:text-white">
      <%= t('activerecord.attributes.catch.new.size_prompt') %>
    </div>
    <div class="bg-gray-50 border border-gray-300 text-gray-900 text-sm md:text-base rounded-lg p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      <%= catch.size %>
    </div>
  </div>

  <!-- Memo -->
  <% if catch.memo.present? %>
    <div class="col-span-2">
      <div class="block mb-2 text-sm md:text-base font-medium text-gray-900 dark:text-white">
        <%= t('activerecord.attributes.catch.new.memo') %>
      </div>
      <div class="bg-gray-50 border border-gray-300 text-gray-900 text-sm md:text-base rounded-lg p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:text-white">
        <%= catch.memo %>
      </div>
    </div>
  <% end %>

  <!-- Google Map -->
  <% if catch.latitude.present? && catch.longitude.present? %>
    <div class="col-span-2">
      <div class="block mb-2 text-sm md:text-base font-medium text-gray-900 dark:text-white">
        <%= t('activerecord.attributes.catch.show.map') %>
      </div>
      <div data-controller="catchshowmap"
          data-catchshowmap-latitude-value="<%= catch.latitude %>"
          data-catchshowmap-longitude-value="<%= catch.longitude %>"
          data-catchshowmap-map-id-value="<%= Rails.application.credentials.google[:maps_id] %>"
          data-catchshowmap-api-key-value="<%= Rails.application.credentials.google[:maps_api_key] %>"
          data-catchshowmap-catch-id-value="<%= catch.id %>">
        <div id="map_<%= catch.id %>" class="rounded-lg map-container h-[300px] md:h-[150px]">
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/catches/_admin_show_images.html.erb
<div id="<%= dom_id(catch, :admin_carousel) %>" class="relative w-full" data-carousel="slide">

  <div class="relative h-72 overflow-hidden rounded-lg md:h-96">
    <% if catch.images.attached? %>
      <% catch.images.each_with_index do |image, index| %>
        <div id="<%= dom_id(image, :admin_slide) %>" class="<%= index.zero? ? '' : 'hidden' %> duration-700 ease-in-out" data-carousel-item>
          <%= image_tag image, class: "absolute block w-full h-full object-cover -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2", alt: "Catch Image" %>
        </div>
      <% end %>

      <!-- Slider indicators -->
      <div class="absolute z-30 flex -translate-x-1/2 bottom-5 left-1/2 space-x-3 rtl:space-x-reverse">
        <% catch.images.each_with_index do |_, index| %>
          <button type="button" class="w-3 h-3 rounded-full" aria-current="<%= index.zero? %>" aria-label="Slide <%= index + 1 %>" data-carousel-slide-to="<%= index %>"></button>
        <% end %>
      </div>

      <!-- Slider controls -->
      <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
          <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4" />
          </svg>
          <span class="sr-only">Previous</span>
        </span>
      </button>
      <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
          <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
          </svg>
          <span class="sr-only">Next</span>
        </span>
      </button>

    <% else %>
      <!-- Default Image -->
      <div class="duration-700 ease-in-out" data-carousel-item>
        <img src="/index.png" class="absolute block w-full h-full object-cover -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="No Image">
      </div>
    <% end %>
  </div>
</div>

app/views/admin/catches/index.html.erb
<div class="py-24 md:pt-8 md:pb-24">
  <!-- Tittle -->
  <div class="flex items-center justify-between max-w-screen-xl mx-auto px-3 mb-6">
    <h5 class="text-lg md:text-xl font-bold leading-none text-gray-900 dark:text-white">Catch Management</h5>
    <a href="<%= admin_dashboard_path %>" class="text-sm md:text-base font-medium text-blue-600 hover:underline dark:text-blue-500">Back to Dashboard</a>
  </div>
  <!-- Card -->
  <%= turbo_frame_tag "admin_catches_page_#{@catches.current_page}" do %>
    <div class="flex flex-col items-center justify-center px-3 w-full max-w-screen-xl mx-auto mb-6">
      <div id="catch_index" class="grid grid-cols-1 lg:grid-cols-2 gap-6 w-full">
        <% @catches.each do |catch| %>
          <%= render 'admin_index_content', catch: catch %>
        <% end %>
      </div>
    </div>

    <% if @catches.next_page %>
      <%= turbo_frame_tag "admin_catches_page_#{@catches.next_page}", src: admin_catches_path(page: @catches.next_page), loading: :lazy %>
    <% end %>
  <% end %>
</div>

app/views/admin/catches/show.html.erb
<%= render 'admin_show', catch: @catch %>