config/routes.rb
Rails.application.routes.draw do
  get "pages/contact"

  resources :diaries do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
  end

  get "index_user", to: "catches#index_user"
  get "index_user/autocomplete", to: "catches#autocomplete_index_user"

  resources :catches do
    member do
      delete :purge_image
    end
    collection do
      get :autocomplete
    end
    resource :like, only: [ :create, :destroy ]
    resources :comments, only: [ :new, :create, :index, :destroy, :edit, :update ]
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root "home#index"

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users
    resources :catches
    resources :diaries
  end

  get "terms", to: "home#terms"
  get "privacy_policy", to: "home#privacy_policy"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash-message-container">
    <div class="flash-message flex items-center w-full max-w-xs p-4 md:max-w-md md:p-6 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert" data-controller="flash">
      <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 md:w-10 md:h-10 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
        <svg class="w-5 h-5 md:w-6 md:h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
        </svg>
      </div>
      <span class="sr-only">Check icon</span>
      <div class="ms-3 text-sm md:text-base font-normal">
        <%= flash[:notice].html_safe %>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash-message-container">
    <div class="flash-message flex items-center w-full max-w-xs p-4 md:max-w-md md:p-6 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert" data-controller="flash">
      <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 md:w-10 md:h-10 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
        <svg class="w-5 h-5 md:w-6 md:h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z"/>
        </svg>
      </div>
      <span class="sr-only">Error icon</span>
      <div class="ms-3 text-sm md:text-base font-normal">
        <%= flash[:alert].html_safe %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="fixed bottom-0 left-0 z-50 w-full h-20 bg-white border-t border-gray-200 dark:bg-gray-900 dark:border-gray-900">
    <div class="grid h-full max-w-screen-xl mx-auto grid-cols-5 font-medium">
    <% if user_signed_in? %>
        <a href="<%= catches_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">全ての釣果</span>
        </a>
        <a href="<%= index_user_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">自分の釣果</span>
        </a>
    <% else %>
        <a href="<%= root_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">ホーム</span>
        </a>
        <a href="<%= catches_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">釣果を見る</span>
        </a>
    <% end %>
        <button type="button" data-modal-target="record-modal" data-modal-toggle="record-modal" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">記録する</span>
        </button>
    <% if user_signed_in? %>
        <a href="<%= diaries_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M11.074 4 8.442.408A.95.95 0 0 0 7.014.254L2.926 4h8.148ZM9 13v-1a4 4 0 0 1 4-4h6V6a1 1 0 0 0-1-1H1a1 1 0 0 0-1 1v13a1 1 0 0 0 1 1h17a1 1 0 0 0 1-1v-2h-6a4 4 0 0 1-4-4Z"/>
                <path d="M19 10h-6a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1Zm-4.5 3.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2ZM12.62 4h2.78L12.539.41a1.086 1.086 0 1 0-1.7 1.352L12.62 4Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">自分の日記</span>
        </a>
        <a href="<%= edit_user_registration_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm0 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 13a8.949 8.949 0 0 1-4.951-1.488A3.987 3.987 0 0 1 9 13h2a3.987 3.987 0 0 1 3.951 3.512A8.949 8.949 0 0 1 10 18Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">マイページ</span>
        </a>
    <% else %>
        <a href="<%= new_user_registration_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">新規登録</span>
        </a>
        <a href="<%= new_user_session_path %>" class="inline-flex flex-col items-center justify-center px-1 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-5 h-5 mb-2 text-gray-500 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 14 20">
                <path d="M13 20a1 1 0 0 1-.64-.231L7 15.3l-5.36 4.469A1 1 0 0 1 0 19V2a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v17a1 1 0 0 1-1 1Z"/>
            </svg>
            <span class="text-xs text-gray-500 md:text-base dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-500">ログイン</span>
        </a>
    <% end %>
    </div>
</div>

<!-- Record modal -->
<div id="record-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full" data-controller="record">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-800">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-sm md:text-base xl:text-lg font-semibold text-gray-900 dark:text-white w-full">
                  <ul class="flex flex-wrap justify-center space-x-4 font-medium text-center" id="record-tab" data-tabs-toggle="#record-tab-content" role="tablist">
                      <li role="catch">
                          <button class="inline-block p-2 border-b-2 rounded-t-lg text-base md:text-lg" id="catch-tab" data-tabs-target="#catch" type="button" role="tab" aria-controls="catch" aria-selected="false">釣果</button>
                      </li>
                      <li role="diary">
                          <button class="inline-block p-2 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 text-base md:text-lg" id="diary-tab" data-tabs-target="#diary" type="button" role="tab" aria-controls="diary" aria-selected="false">日記</button>
                      </li>
                  </ul>
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="record-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 pt-0 md:p-5 md:pt-0 space-y-4">
              <div id="record-tab-content">
                  <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="catch" role="tabpanel" aria-labelledby="catch-tab">
                    <%= turbo_frame_tag "new_catch_form", src: new_catch_path(format: :turbo_stream) %>
                  </div>
                  <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="diary" role="tabpanel" aria-labelledby="diary-tab">
                    <%= turbo_frame_tag "new_diary_form", src: new_diary_path(format: :turbo_stream) %>
                  </div>
              </div>
            </div>
            <!-- Modal footer -->
            <div class="flex items-center justify-end p-4 md:p-5 space-x-3 rtl:space-x-reverse border-t border-gray-200 rounded-b dark:border-gray-600">
                <button data-modal-hide="record-modal" type="button" class="py-2.5 px-5 ms-3 text-sm md:text-base font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">閉じる</button>
            </div>
        </div>
    </div>
</div>

app/views/shared/_header.html.erb
<header class="mobile-only fixed top-0 left-0 w-full z-50">
  <nav class="border-gray-200 bg-gray-50 dark:bg-gray-900 dark:border-gray-700">
    <div class="mx-auto">
      <div class="flex flex-wrap items-center justify-between p-2">
        <a href="<%= root_path %>" class="flex items-center space-x-2 rtl:space-x-reverse">
          <%= image_tag "/icon_white.svg", class: "h-10", alt: "Fishingram Logo" %>
          <%= image_tag "/banner_white_subtitle.svg", class: "h-10", alt: "Fishingram Banner" %>
        </a>
        
        <!-- New Dropdown Button -->
        <button id="dropdownMenuIconHorizontalButton" data-dropdown-toggle="dropdownDotsHorizontal" class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-900 dark:hover:bg-gray-700 dark:focus:ring-gray-600" type="button">
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
            <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
          </svg>
        </button>

        <!-- Dropdown menu -->
        <div id="dropdownDotsHorizontal" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-800 dark:divide-gray-600">
          <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownMenuIconHorizontalButton">
            <li>
              <%= link_to '利用規約', terms_path, class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
            </li>
            <li>
              <%= link_to 'プライバシーポリシー', privacy_policy_path, class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
            </li>
            <li>
              <%= link_to '問い合わせ', 'https://docs.google.com/forms/d/e/1FAIpQLSfo8LgIDTyXKO3_wR37ONSLzs22f3wBH7_B1SWHbex0SJQOOA/viewform', target: '_blank', class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
              </li>
            <% end %>
            <% if current_user && current_user.admin? %>
              <li>
                <%= link_to 'Admin Dashboard', admin_dashboard_path, class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

<header class="tablet-pc-only bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="<%= root_path %>" class="flex items-center space-x-2 rtl:space-x-reverse">
      <%= image_tag "/icon_white.svg", class: "h-14", alt: "Fishingram Logo" %>
      <%= image_tag "/banner_white_subtitle.svg", class: "h-14", alt: "Fishingram Banner" %>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="<%= terms_path %>" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">利用規約</a>
        </li>
        <li>
          <a href="<%= privacy_policy_path %>" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">プライバシーポリシー</a>
        </li>
        <li>
          <a href="https://docs.google.com/forms/d/e/1FAIpQLSfo8LgIDTyXKO3_wR37ONSLzs22f3wBH7_B1SWHbex0SJQOOA/viewform" target="_blank" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">問い合わせ</a>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
        <% end %>
        <% if current_user && current_user.admin? %>
          <li>
            <%= link_to 'Admin Dashboard', admin_dashboard_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>